### PR TITLE
Reconnect to BitMex if the websocket disconnects

### LINKED ISSUE #919: The maker does not reconnect after losing the WebSocket connection to BitMEX
When the maker loses connection to the WebSocket, it does not try to reconnect. As a result, we do not send any limit orders anymore.

Only the scheduled restart fixes that.

```
{"timestamp":"2023-07-05T21:22:15.109143768Z","level":"DEBUG","fields":{"message":"Received new quote","bid":"30436","ask":"30436.5","timestamp":"2023-07-05 21:22:00.0 +00:00:00","symbol":"btcusd"},"target":"maker::trading::bitmex_client"}
{"timestamp":"2023-07-05T21:22:15.109175842Z","level":"DEBUG","fields":{"message":"Received new quote Quote { timestamp: \"2023-07-05T21:22:00Z\", bid: 30436, ask: 30436.5 }"},"target":"maker::trading"}
{"timestamp":"2023-07-05T21:23:11.387348853Z","level":"DEBUG","fields":{"message":"Received close frame: Some(CloseFrame { code: Away, reason: \"CloudFlare WebSocket proxy restarting\" })","log.target":"tungstenite::protocol","log.module_path":"tungstenite::protocol","log.file":"/home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tungstenite-0.18.0/src/protocol/mod.rs","log.line":556},"target":"tungstenite::protocol"}
{"timestamp":"2023-07-05T21:23:11.387384049Z","level":"DEBUG","fields":{"message":"Replying to close with Frame { header: FrameHeader { is_final: true, rsv1: false, rsv2: false, rsv3: false, opcode: Control(Close), mask: None }, payload: [3, 233, 67, 108, 111, 117, 100, 70, 108, 97, 114, 101, 32, 87, 101, 98, 83, 111, 99, 107, 101, 116, 32, 112, 114, 111, 120, 121, 32, 114, 101, 115, 116, 97, 114, 116, 105, 110, 103] }","log.target":"tungstenite::protocol","log.module_path":"tungstenite::protocol","log.file":"/home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tungstenite-0.18.0/src/protocol/mod.rs","log.line":573},"target":"tungstenite::protocol"}
```

### PR DESCRIPTION
**Pull request by Restioson**
Adds a timeout to the websocket to bitmex in order to provoke a reconnect if the websocket becomes unresponsive. Fixes #919.

### CODE REVIEW

**Comment by Restioson** [comment]
I'm wondering why [this](https://github.com/get10101/10101/blob/main/maker/src/trading/bitmex_client.rs#L17) piece of code would not already work to reconnect to bitmex?

**Review by bonomat — APPROVED** [review]
Let's get this in. Thank you.

**Pull request merged**
