### PR TITLE
feat: Add initial web layout

### PR DESCRIPTION
**Pull request by holzeis**
Screenshot 2024-01-18 at 13 07 35

### CODE REVIEW

**Comment by bonomat** [comment]
@holzeis : I've added [`52d6586` (#1832)](https://github.com/get10101/10101/pull/1832/commits/52d658614484a80c568605afc85970e4d97d6c08). It's a responsive design and will switch to a bottom navigation bar when moving smaller than 450pixel



https://github.com/get10101/10101/assets/224613/9206128f-fa0e-421c-a008-ce296ab1c2f7

**Comment by holzeis** [comment]
Also it doesn't really "feel" like a web experience either 🙈.

**Comment by bonomat** [comment]
> Also it doesn't really "feel" like a web experience either 🙈.

I mean, who opens websites on a widescreen in fullscreen mode 🙈 

I guess in the ultra wide one should switch to something different. This is from the material design specs: 

> Use a [navigation bar](https://m3.material.io/m3/pages/navigation-bar/overview) in compact [window sizes](https://m3.material.io/m3/pages/applying-layout/window-size-classes/m3/pages/applying-layout/window-size-classes). 
> 
> Use a navigation rail in medium and expanded window sizes.  
> 
> Use either a navigation rail or a standard [navigation drawer](https://m3.material.io/m3/pages/navigation-drawer/overview) in large and extra-large window sizes.

**Comment by holzeis** [comment]
Let's go for it 👍

**Review by bonomat — APPROVED** [review]
Let's go

**Pull request merged**
