### PR TITLE
chore: listen on broadcast address

### PR DESCRIPTION
**Pull request by bonomat**
The problem on our VM was that we could not listen on our public ip address from inside the container. Instead, we should listen on 0.0.0.0

### CODE REVIEW

**Review by luckysori — APPROVED** [review]
Nice! Let's roll with this.

**Review by da-kami — APPROVED** [review]

**Comment by bonomat** [comment]
bors retry

**Comment by holzeis** [comment]
> The problem on our VM was that we could not listen on our public ip address from inside the container. Instead, we should listen on 0.0.0.0

I guess that's a change that wasn't transferred to the the cloud-conf. I also noticed that we can't bind on our public ip and changed to `0.0.0.0`. Your fix is still better though, as it will allow us now to separate the node announcement from how to listen. 👍

**Pull request merged**
