### PR TITLE
feat: Add close button to dialog if it remains in pending for more than 30 seconds

### LINKED ISSUE #1108: `OrderSubmissionStatusDialog` can hang forever
If the subchannel open/close protocol does not finish (either successfully or unsuccessfully), the `OrderSubmissionStatusDialog` will remain open indefinitely.

This is a problem because the same dialog says that the user should not close the app, but that's the only way to move forward.

### PR DESCRIPTION
**Pull request by holzeis**
fixes #1108

### CODE REVIEW

**Review by bonomat — COMMENTED** [review]
Am I understanding it right, that the dialog will simply show `failed` after `30` seconds?
If so, what about the task in the backend? It might still succeed nevertheless .

**Comment by holzeis** [comment]
> Am I understanding it right, that the dialog will simply show `failed` after `30` seconds? If so, what about the task in the backend? It might still succeed nevertheless .

If it succeeds, it succeeds and we are happy. It still took a very long time and the user should be free to close the dialog after some time.

Do you prefer a dedicated icon / status for timeout? I was think to also add the share log button if we run into a dialog. So the user can directly report an issue.

Alternatively we could as well simply show a close button while we keep the pending animation.

**Comment by bonomat** [comment]
> If it succeeds, it succeeds and we are happy. It still took a very long time and the user should be free to close the dialog after some time.

Just to clarify: it will not show as failed, but the user can just close the dialog instead?

**Comment by holzeis** [comment]
> > If it succeeds, it succeeds and we are happy. It still took a very long time and the user should be free to close the dialog after some time.
> 
> Just to clarify: it will not show as failed, but the user can just close the dialog instead?

If the task succeeds before the timeout, it will not show failed if thats what you are concerned about. The timer gets cancelled if we receive a `TaskStatus` other than `Pending`.

**Comment by bonomat** [comment]
> > > If it succeeds, it succeeds and we are happy. It still took a very long time and the user should be free to close the dialog after some time.
> > 
> > 
> > Just to clarify: it will not show as failed, but the user can just close the dialog instead?
> 
> If the task succeeds before the timeout, it will not show failed if thats what you are concerned about. The timer gets cancelled if we receive a `TaskStatus` other than `Pending`.

No, I'm concerned about the situation where it succeeds after the timeout.

**Comment by holzeis** [comment]
> No, I'm concerned about the situation where it succeeds after the timeout.

Any suggestion on how you would deal with a timeout then?

**Review by bonomat — APPROVED** [review]
Looks good. Let's get this in.

**Pull request merged**
