### PR TITLE
Change "Unrealized P/L" to "P/L" when order closes position and is filled

### PR DESCRIPTION
**Pull request by Restioson**
Addresses #871 but does not calculate the realized P/L from the channel as per #895 (see Daniel's comment on #871).

### CODE REVIEW

**Review by da-kami — APPROVED** [review]
I think this might be good enough for now.

It could still be that a wrong realized P/L is shown, but in my understanding only if the price moves very fast (and the execution price becomes outdated).

**Comment by da-kami** [comment]
@Restioson please wait for the review from @holzeis though, I am not sure he had something else in mind :)

**Comment by holzeis** [comment]
hmm I was thinking of actually using the value calculated during closing a position and returning it to the frontend to show the realized pnl.

https://github.com/get10101/10101/blob/1c62f9eeafa231d8c3b807ea101e70d53e8fc3c4/coordinator/src/node.rs#L255-L274

But I guess that might not make a big difference to what we currently have.

**Comment by da-kami** [comment]
> hmm I was thinking of actually using the value calculated during closing a position and returning it to the frontend to show the realized pnl.
> 
> https://github.com/get10101/10101/blob/1c62f9eeafa231d8c3b807ea101e70d53e8fc3c4/coordinator/src/node.rs#L255-L274
> 
> But I guess that might not make a big difference to what we currently have.

The execution is assumed to be based on the execution price anyway - this execution price comes from the orderbook match. The coordinator does not decide the execution price - unless it is a scenario where the position is expired ([see this code for reference](https://github.com/get10101/10101/blob/ba3b50fb8613c956617bb638d4cb5c28851a437b/coordinator/src/bin/coordinator.rs#L150-L201)). But this case is not relevant for this ticket, because the user does not see this success dialog then - and the coordinator triggering a collab close a workaround for the beta after expiry.

If we would associate the orders with our positions correctly already we should just know the execution price and could use it for the calculation.  I don't think we have to return anything from the coordinator to the app, but we have to make the `Position` aware of its closing order (or at least the closing price).

The `pnl` in the `Position` in the UI is currently not aware of orders, it is set here:

https://github.com/get10101/10101/blob/770ed5db32e68ecd4817a6d5637a1b82e1d3b9cf/mobile/lib/features/trade/trade_screen.dart#L53-L58

which falls back to the `PositionChangeNotifier` where we update the pnl based on the latest price.

https://github.com/get10101/10101/blob/caf534d24e1973b6c445ca25f9afb22d8464ddf0/mobile/lib/features/trade/position_change_notifier.dart#L30-L62

In order to use the execution price we would have to make the position aware of its closing order and then lock in the price based on that order instead of using the current price. 

---

@Restioson sorry I did not see this part that clearly in our discussion yesterday.

To achieve using the closing price in a simple way you can:

1. Add some kind of `closing_price` to the `Position`
2. Set this `closing_price` when we update the position in [`update_position_after_order_submitted`](https://github.com/get10101/10101/blob/01f393c2efebfbed45ff61f5d8850a21cb6484f5/mobile/native/src/trade/position/handler.rs#L64-L76); which includes adding the optional `closing_price` to the model so it is communicated in `PositionUpdateNotification`.
3. Add logic to not update the `PnL` if the `closing_price` in the UI `Position1 is not null.

Note: This assumes that the order will be executed with the `closing_price` - if we fail the order execution we would have to not only reset the position to `Open`, but also remove the `closing_price` so we have an unrealized PnL again. We definitely don't always do that (i.e. we don't always re-open a position if the order execution fails), but adding the `closing_price` won't make this any worse, so we can treat that as a separate problem :)

**Comment by da-kami** [comment]
@holzeis after our discussion I think this PR is ready to merge

I captured potential follow-up work here: https://github.com/get10101/10101/issues/922

Feel free to approve and merge :)

**Review by holzeis — APPROVED** [review]

**Pull request merged**
