### PR TITLE
feat: Get rid of buy and sell tabs

### LINKED ISSUE #2351: Get rid of BUY/SELL tab and add a BUY and SELL button under the trade configurator

### PR DESCRIPTION
**Pull request by holzeis**
Since we do not know the direction, the liquidation price and margin has been moved to the confirmation dialog.

Therefore, the new order confirmation dialog has also been introduced when opening a new channel.

|	|	|
|:-:|:-:|
| Screenshot 2024-04-09 at 13 18 23 |  Screenshot 2024-04-09 at 16 05 38 |

fixes #2351

### CODE REVIEW

**Review by bonomat — COMMENTED** [review]
I'm not a fan of this new design :/ 

I think it has lots of value to see the margin requirements and liqidation point right when entering things. 

But as you said, if we have two button we can't calculate this... Maybe this means we shouldn't do this change then?

**Comment by holzeis** [comment]
> I'm not a fan of this new design :/
> 
> I think it has lots of value to see the margin requirements and liqidation point right when entering things.
> 
> But as you said, if we have two button we can't calculate this... Maybe this means we shouldn't do this change then?

I am impartial about that, I am fine either way. I think the web app can use some face lifts in general. This doesn't make a huge difference to me 😅

**Comment by holzeis** [comment]
@bonomat Please let me know if we want this in or not.

**Comment by bonomat** [comment]
we could ask UAP, but overall I'm against it.

**Pull request closed without merging**
