### PR TITLE
fix: signing a message using our nodes key

### PR DESCRIPTION
**Pull request by bonomat**
this seems to be the correct function to use.

It works, i.e. you can sign, but I did not manage to log into amboss or lightningswap yet :)

### CODE REVIEW

**Comment by bonomat** [comment]
@holzeis : tested locally with correct key and it works

**Comment by bonomat** [comment]
- https://amboss.space/node/022ae8dbec1caa4dac93f07f2ebf5ad7a5dd08d375b79f11095e81b065c2155156
- https://lightningnetwork.plus/nodes/022ae8dbec1caa4dac93f07f2ebf5ad7a5dd08d375b79f11095e81b065c2155156

**Review by holzeis — APPROVED** [review]
Awesome 👍

**Pull request merged**
