### PR TITLE
chore: Bump webapp in dedicated step

### PR DESCRIPTION
**Pull request by holzeis**
Also remove changelog and changelog action

### CODE REVIEW

**Review by luckysori — APPROVED** [review]
Nice!

**Review by bonomat — APPROVED** [review]

**Review by bonomat — CHANGES_REQUESTED** [review]
I believe you will need to adjust `create_release.yml` as well as it requires the changelog file

https://github.com/get10101/10101/blob/3c45dd3f2325c2082067e4fde6ab7c8cf98a8e33/.github/workflows/create_release.yml#L24-L28

**Comment by holzeis** [comment]
> I believe you will need to adjust `create_release.yml` as well as it requires the changelog file
> 
> https://github.com/get10101/10101/blob/3c45dd3f2325c2082067e4fde6ab7c8cf98a8e33/.github/workflows/create_release.yml#L24-L28

This has already been removed on main - https://github.com/get10101/10101/blob/main/.github/workflows/create_release.yml

**Comment by bonomat** [comment]
> > I believe you will need to adjust `create_release.yml` as well as it requires the changelog file
> > https://github.com/get10101/10101/blob/3c45dd3f2325c2082067e4fde6ab7c8cf98a8e33/.github/workflows/create_release.yml#L24-L28
> 
> This has already been removed on main - [`main`/.github/workflows/create_release.yml](https://github.com/get10101/10101/blob/main/.github/workflows/create_release.yml?rgh-link-date=2024-03-06T09%3A47%3A24Z)

Oh, sorry for that

**Review by bonomat — APPROVED** [review]

**Pull request merged**
