### PR TITLE
chore: mainnet candle stick chart

### PR DESCRIPTION
**Pull request by bonomat**
Mainnet looks better than the testnet version which comes handy when doing demo videos or screenshots.

I keep changing this manually when I need quickly some screenshots so I thought I'd just change this permanently. 
Downside: the price will now be different to what the chart shows.

### CODE REVIEW

**Comment by holzeis** [comment]
> Downside: the price will now be different to what the chart shows.

Why not also create the orders from the mainnet bitmex stream?

**Comment by bonomat** [comment]
> > Downside: the price will now be different to what the chart shows.
> 
> Why not also create the orders from the mainnet bitmex stream?

it wil eventually mess with our maker and hedging strategy.

**Review by Restioson — APPROVED** [review]

**Comment by holzeis** [comment]
> it wil eventually mess with our maker and hedging strategy.

That's confusing to me, can you elaborate on that. How will it mess with the hedging strategy?

**Comment by bonomat** [comment]
> > it wil eventually mess with our maker and hedging strategy.
> 
> That's confusing to me, can you elaborate on that. How will it mess with the hedging strategy?

If we want to track that or testnet maker makes money we need to take the prices what are currently being traded on testnet.bitmex.com and not the prices from mainnet bitmex.com

**Review by holzeis — APPROVED** [review]
Lets give it a go!

**Pull request merged**
