### PR TITLE
Add firebase analytics

### PR DESCRIPTION
**Pull request by klochowicz**

### CODE REVIEW

**Review by bonomat — CHANGES_REQUESTED** [review]
Shall we try one new feature at a time? 
At the moment I'm still fighting with getting a release done with the initial firebase changes.

**Comment by klochowicz** [comment]
> Shall we try one new feature at a time?
> At the moment I'm still fighting with getting a release done with the initial firebase changes.

I absolutely don't mind waiting for the notifications to get rolled out first. No rush with getting this one in, the changes are pretty self-contained. 

Will request re-review after the release.

**Comment by klochowicz** [comment]
@bonomat is the initial firebase release out, ie. shall I rebase I merge it?

**Comment by bonomat** [comment]
> @bonomat is the initial firebase release out, ie. shall I rebase I merge it?

Let's focus on something which is in the pipeline first please.

**Comment by klochowicz** [comment]
Closing this PR after @bonomat confirmed that he's against it if it requires us to fix a few things around Flutter routing.
See: 
https://github.com/get10101/10101/pull/1144#issuecomment-1690427364

We can always reopen this later, if we decide  would like to have this functionality and are willing to refactor a bit of Flutter code.

**Comment by holzeis** [comment]
@klochowicz is this really related to #1144 ?

**Comment by klochowicz** [comment]
> @klochowicz is this really related to #1144 ?

Thank you for the message and prompting me into looking into it deeper! I haven't looked into it in detail for a while, I only remembered that it changes `GoRouter` settings. #1144 changed the router settings and introduced side-effects.

After thinking about it more, allow me to rephrase it :
It *should not* impact it, especially that here we're only adding it as an observer, not wrapping the router with another entity. Then again, feedback widget also should not impact that 😅

**Comment by klochowicz** [comment]
I'm closing this for  now is it's not immediate priority.

**Pull request closed without merging**
