### PR TITLE
Only generate flutter bindings when needed

### PR DESCRIPTION
**Pull request by klochowicz**
- flutter bindings are needed only for native, iOS and Android builds 
- CI test jobs, notably tests do not benefit from them
- we can save time by not compiling them

### CODE REVIEW

**Comment by klochowicz** [comment]
I realised that this should be done in conjunction with having smoke tests for iOS and Android - there is a chance of them being broken.

**Review by holzeis — APPROVED** [review]
LGTM 👍

**Review by luckysori — APPROVED** [review]
Very nice!

**Comment by holzeis** [comment]
@klochowicz is there a lot left to be done? or can we get this in after resolving the conflicts?

**Comment by klochowicz** [comment]
> @klochowicz is there a lot left to be done? or can we get this in after resolving the conflicts?

I was hoping to only push this when smoke tests are done; otherwise, we need to make sure we can build on iOS/Android still after a `just clean`. 

Will rebase today.

**Comment by Restioson** [comment]
> I was hoping to only push this when smoke tests are done; otherwise, we need to make sure we can build on iOS/Android still after a `just clean`.

Anecdote: I opened #1048 because the bindings hadn't changed in a while so I didn't realise that my `libnative.so` was a week or more out of date :sweat_smile: Probably no structured way to test it though.

This change looks good, FRB can take up a lot of time in the build process!

**Comment by klochowicz** [comment]
> > I was hoping to only push this when smoke tests are done; otherwise, we need to make sure we can build on iOS/Android still after a `just clean`.
> 
> Anecdote: I opened #1048 because the bindings hadn't changed in a while so I didn't realise that my `libnative.so` was a week or more out of date 😅 Probably no structured way to test it though.
> 
> This change looks good, FRB can take up a lot of time in the build process!
> 
> I wonder if there could be a followup, similar PR which only regenerates the bindings if the public-facing api of the `native` crate changes?

I tried to rebase it & test it and run into some issues with it ;/ (it turns out that it as it stands currently it needs the bindings to be built at least once, so the whole PR is kinda pointless...).
It would be a "nice-to-have" and I cannot justify the time working on this.

Closing this PR for now, maybe someday we'll pick it up again.

**Pull request closed without merging**
