### PR TITLE
fix: remove feedback plugin

### LINKED ISSUE #1152: Dialog can now be clicked away
Changing the `useRootNavigator` to `false` broke the feature of not being able to click away the loading dialog while a position is being opened. 

Differently said, you can now click on the bottom bar to navigate away from the loading dialog and warning will be closed. 

https://github.com/get10101/10101/assets/224613/b82dacff-e1b6-437e-a8c1-f6454bc551c2

### PR DESCRIPTION
**Pull request by bonomat**
I can confirm, the feedback plugin breaks the account drop down. Since it also broke other places in the code, e.g. the confirm dialog after trade which required an extra fix I went ahead and removed it again.

By removing the feedback plugin we don't need those fixes neither. All of this was undone in this commit.

reverts 13d1a48b1c03d9c699464526088e8b2f692b84d1
reverts 8fb02bafb16bbe58364e4ab2b03c443f60881e9c

Resolves https://github.com/get10101/10101/issues/1129
Resolves https://github.com/get10101/10101/issues/1131
Resolves #1152

Tested in the manually deployed version 
- build: 1
- version 1.2.2
- commit 3620a3ebe47e8365b5c19d42f7b269b62c611712

### CODE REVIEW

**Review by klochowicz — CHANGES_REQUESTED** [review]
please separate the fixes for feedback plugin from removing the functionality.

if you've read the commit descriptions, then you might have read that we have been using wrong way to bring things to the front and it would have break itself then too (ie. we'll need for #1104 ).

**Comment by klochowicz** [comment]
it's sad to see a piece of functionality aimed to get feedback from our users go, but it's ultimately your call of course.

Just to confirm: the account overview was the only outstanding problem, yes? You do realise that the other one was due to our lack of proper usage of Flutter as we cobbled things together very quickly, and perhaps this one was too?

**Comment by bonomat** [comment]
> Just to confirm: the account overview was the only outstanding problem, yes? You do realise that the other one was due to our lack of proper usage of Flutter as we cobbled things together very quickly, and perhaps this one was too?

Unfortunately I found another bug which was caused by this: https://github.com/get10101/10101/issues/1152. Not critical but it's unfortunately not clear what else is broken because of the changes related to the plugin.

**Comment by klochowicz** [comment]
just to confirm @bonomat - you don't want the #1104 to lang anytime soon either? because this will likely trigger the same fixes needed (I'm happy to take care of them all in a comprehensive way, which I believe being the best way forward, ie. understanding Flutter usage more.

**Review by holzeis — APPROVED** [review]
Let's remove this for now so we unblock other things and come back to it another time by also addressing the bugs that this feedback plugin has introduced.

**Comment by Restioson** [comment]
> Let's remove this for now so we unblock other things and come back to it another time by also addressing the bugs that this feedback plugin has introduced.

I think it would be a good idea to write up a list of bugs somewhere along with steps to reproduce so we can test it on the next  relevant PR

**Pull request merged**
