### PR TITLE
Release version 1.2.0

### PR DESCRIPTION
**Pull request by 1010Tom**
Hi @bonomat!
This PR was created in response to a manual trigger of the release workflow here: https://github.com/get10101/10101/actions/runs/5762281370.
I've bumped the versions in the manifest files in this commit: 0533ac91c7c17614dd447fbfb1c33f63792988e6.
Merging this PR will create a GitHub release!

closes https://github.com/get10101/10101/milestone/3

### CODE REVIEW

**Review by klochowicz — APPROVED** [review]

**Comment by bonomat** [comment]
Needs a rebase after https://github.com/get10101/10101/pull/1064 was merged.
I'd say https://github.com/get10101/10101/issues/1031 can go into the a patch release so that we can trigger a release over the weekend and have it reviewed till monday.

**Comment by holzeis** [comment]
maybe blocked by https://github.com/get10101/10101/issues/1074 ?

**Comment by bonomat** [comment]
> maybe blocked by #1074 ?

Do you believe it is a regression which came in between 1.1.0 and now? If not, I'd say this is a "normal" bug which we need to fix but independently of 1.2.0

**Comment by holzeis** [comment]
> > maybe blocked by #1074 ?
> 
> Do you believe it is a regression which came in between 1.1.0 and now? If not, I'd say this is a "normal" bug which we need to fix but independently of 1.2.0

well, i don't know. It looks like it. Downgrading to 1.1.0 (1726) is also crashing my app. Obviously it's not happening in all scenarios.. Maybe we release and check if it happens as well on the main version. If so, we don't have to publish it for external users and work on a patch.

**Comment by bonomat** [comment]
Rebased!

**Pull request merged**
