### PR TITLE
Extend coordinator HTP API

### PR DESCRIPTION
**Pull request by 1010Tom**
resolves https://github.com/get10101/10101/issues/406

### CODE REVIEW

**Review by holzeis — APPROVED** [review]
Nice 👌

**Comment by 1010Tom** [comment]
bors retry

**Comment by 1010Tom** [comment]
@klochowicz / @holzeis : could you have a quick look please why CI is failing here? I don't see it :/

**Comment by holzeis** [comment]
bors retry

**Comment by 1010Tom** [comment]
bors retry

**Comment by klochowicz** [comment]
> @klochowicz / @holzeis : could you have a quick look please why CI is failing here? I don't see it :/

it's been intermittently happening for a while: https://github.com/get10101/10101/issues/355

**Pull request merged**
