### PR TITLE
Display the order according to it's state

### PR DESCRIPTION
**Pull request by da-kami**
- Some beautifying
- Display the execution price if it is set

image

### CODE REVIEW

**Comment by da-kami** [comment]
For a nicer display of double values (i.e. no `.0` display) I created a separate ticket: https://github.com/get10101/10101/issues/161

**Comment by da-kami** [comment]
Expandable Order tracked here: https://github.com/get10101/10101/issues/163

**Review by bonomat — APPROVED** [review]
Looking really nice already :)

**Pull request merged**
