### PR TITLE
feat: allow paying to BIP21 URI

### LINKED ISSUE #1289: Send on-chain payments from on-chain funds
The user should be able to send payments to on-chain addresses using their on-chain funds.

### PR DESCRIPTION
**Pull request by Restioson**
Fixes #1289. #1290 (configure fee) will likely be split out from this PR.

Still WIP:
- [ ] More thorough testing
    - [ ] Test if you can pay from one 10101 wallet to another
- [ ] Support paying to raw addresses (i.e. no amount specified) - split this out from this PR or no?

### CODE REVIEW

**Comment by Restioson** [comment]
I've started looking at how to implement paying to raw addresses, and I saw there is a note elsewhere in the code stating "Invoices without amount are not supported yet". This makes me wonder what is blocking that - if it's just the UI to enter your own amount, maybe I could tackle that in a unified manner for both 0-amount lightning invoices & bare addresses?

**Comment by bonomat** [comment]
> I've started looking at how to implement paying to raw addresses, and I saw there is a note elsewhere in the code stating "Invoices without amount are not supported yet". This makes me wonder what is blocking that - if it's just the UI to enter your own amount, maybe I could tackle that in a unified manner for both 0-amount lightning invoices & bare addresses?

Where is this note you are talking about please?

**Comment by Restioson** [comment]
> Where is this note you are talking about please?

In the send payment screen: https://github.com/get10101/10101/blob/e965c96d8d7988f4cdf3e4c950928ce0dab9a1f7/mobile/lib/features/wallet/send_payment_screen.dart#L188

**Comment by holzeis** [comment]
Invoices without an amount should be fine now. I think this a legacy of when we had the onboarding and create invoice flow in one.

**Pull request closed without merging**
