### PR TITLE
Share to twitter only

### LINKED ISSUE #824: Share on Twitter should share to Twitter only
Currently, the share on twitter button just shares to text generically. While this is okay, it's slightly confusing since the share text refers to twitter specific conventions (like @ and #) . The [social_share](https://pub.dev/packages/social_share) package could be used to target this to twitter only.

The existing text share could remain but be rephrased not to be so twitter-specific, e.g tagging get10101 could be replaced with a link to http://10101.finance/. As an aside, we should _not_ include http://10101.finance/ as a link in the tweet, since apparently this is can be bad for the algorithm - maybe only applies to some TLDs, but I've seen issues with tweets with certain links not being promoted at all.

### PR DESCRIPTION
**Pull request by Restioson**
Use the `social_share` package to share directly and specifically to twitter instead of opening a general share dialogue. This PR is currently a draft since I haven't been able to test this on the Android emulator due to unrelated problems with its setup. 

Fixes #824.

### CODE REVIEW

**Comment by da-kami** [comment]
I tested this on my Pixel and this works like a charm! 

When I hit the `Share on Twitter` button in the 10101 app after successfully opening a position Twitter app comes up directly and I have a pre-filled tweet screen:

image

---

Some notes:

I used the fix in #901 to deploy to my phone with `just run-local-android`.
I was unable to use the `Pay the invoice with 10101 faucet` button - but I am not entirely sure why. When I copied the invoice and directly paid it from the faucet on my machine. The payment then worked and I was able to open a position to test the `Share on Twitter` changes.

**Comment by Restioson** [comment]
I am going to give this a last shot at testing on my emulator, otherwise I suppose this is ready for review and then merge. I would really like to be able to test it locally to certify that it works

**Comment by Restioson** [comment]
I've been digging into this and will report my findings shortly - to expand on what @da-kami said earlier, this is the error when trying to fund using 10101 wallet: 
image

**Comment by Restioson** [comment]
This works on my end, too! :tada: If twitter is not installed, it redirects to the twitter.com page open in the browser. This is good to know, too.

**Comment by bonomat** [comment]
> I've been digging into this and will report my findings shortly - to expand on what @da-kami said earlier, this is the error when trying to fund using 10101 wallet: image

Welcome to the club 😥 I'm getting the same error locally and I can't get it working anymore.

**Comment by bonomat** [comment]
> This works on my end, too! 🎉 If twitter is not installed, it redirects to the twitter.com page open in the browser. This is good to know, too.

Awesome, if it works. Let's get it in.

**Review by bonomat — APPROVED** [review]
LGTM

**Comment by klochowicz** [comment]
> I've been digging into this and will report my findings shortly - to expand on what @da-kami said earlier, this is the error when trying to fund using 10101 wallet:
> image

are you rebased on top of latest changes?

**Comment by Restioson** [comment]
When running on desktop, I get this when trying to share with Twitter:

```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method shareTwitter on channel social_share)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:308:7)
<asynchronous suspension>
#1      SocialShare.shareTwitter (package:social_share/social_share.dart:125:29)
<asynchronous suspension>
#2      TradeScreen.shareTweet (package:get_10101/features/trade/trade_screen.dart:397:5)
<asynchronous suspension>
#3      TradeScreen.createSubmitWidget.<anonymous closure> (package:get_10101/features/trade/trade_screen.dart:386:15)
<asynchronous suspension>
```

Maybe this is allowable as we are only targeting mobile? A fallback might not be _too_ hard to implement, though...

**Comment by Restioson** [comment]
Added a fallback to just use the old solution if platform isn't IOS or Android (SocialShare only works on those two).

**Review by da-kami — APPROVED** [review]

**Comment by holzeis** [comment]
@Restioson may I ask you to add a changelog entry for that change? thank you.

**Review by bonomat — APPROVED** [review]
Looks good. Let's go

**Comment by bonomat** [comment]
> @Restioson may I ask you to add a changelog entry for that change? thank you.

I did it for you :) 

bors r+

**Comment by Restioson** [comment]
> > @Restioson may I ask you to add a changelog entry for that change? thank you.
> 
> I did it for you :)
> 
> bors r+

Thanks!

**Comment by Restioson** [comment]
Closing as this has been merged

**Pull request closed without merging**
