### PR TITLE
feat: use mempool.space as block explorer

### PR DESCRIPTION
**Pull request by bonomat**
Hard to say if this will have a performance impact or not without deploying and trying it out :)

Related to https://github.com/get10101/meta/issues/164.

We can of course try it out manually first.

### CODE REVIEW

**Comment by holzeis** [comment]
Note: this will only change the esplora endpoint for the mobile apps, the coordinator would still go against blockstream.info. The more critical IMHO is the coordinator though. I would simply do a manual test on production and run it against mempool.space to see if the situtation changes.

**Review by luckysori — APPROVED** [review]
I'm happy to try it, but mempool is also rate-limited. I've no idea if the limits are any better. Could we use a mix of both?

**Comment by klochowicz** [comment]
can we get indication what are the rate limits on both? they might be different!

**Comment by luckysori** [comment]
> can we get indication what are the rate limits on both? they might be different!

I think both are undisclosed.

**Comment by bonomat** [comment]
Converting this back to draft: I tried it on the coordinator and it got stuck. I assume we will get a similar result in the app.

**Comment by holzeis** [comment]
@bonomat whats the status of this PR?

**Comment by bonomat** [comment]
We can close this and pick it up again in the future.

**Pull request closed without merging**
