### PR TITLE
chore: Minor improvements on the wallet screen

### PR DESCRIPTION
**Pull request by holzeis**
Obviously a subjective change, but IMHO it's an improvement.

1. Aligned the settings icon with the balance box below
2. Made 10101 logo icon transparent
3. Removed scanner icon as it was only pointing to an empty scanner screen
4. Removed gradient colors and boxes from lightning and on-chain balances.

Screenshot 2023-07-23 at 10 44 41

### CODE REVIEW

**Review by bonomat — APPROVED** [review]
Works for me :)

**Comment by klochowicz** [comment]
I like the first 3 out of 4; the gradient IMHO looked nicer. other than that, excellent improvement.

**Comment by holzeis** [comment]
> I like the first 3 out of 4; the gradient IMHO looked nicer. other than that, excellent improvement.

@klochowicz do you mind merging it as is, or do you want me to bring back the gradient colors?

**Comment by klochowicz** [comment]
> > I like the first 3 out of 4; the gradient IMHO looked nicer. other than that, excellent improvement.
> 
> @klochowicz do you mind merging it as is, or do you want me to bring back the gradient colors? Happy to change it back if you feel strongly about it.. 🙂

I would prefer if we didn't change that bit, thank you for double-checking :)

**Comment by holzeis** [comment]
Note, reintroduced the gradient styling again.

**Pull request merged**
