### PR TITLE
chore: Use network specific quotes everywhere

### PR DESCRIPTION
**Pull request by holzeis**
Use the correct quotes consistently on the coordinator and app depending on the network.

// edit: updated description due to a changed solution approach.

### CODE REVIEW

**Review by da-kami — APPROVED** [review]
Happy to role with this - as long as you don't actually test hedging against testnet bitMEX this will be fine :)

**Comment by bonomat** [comment]
Not against it but it will mess with our hedging strategy.

**Comment by holzeis** [comment]
Alternatively, we can also use the testnet quotes consistently. e.g. the candlestick chart always shows mainnet prices. Also the testnet quotes do not change that often, thats why I sometime thought the maker was down.

**Comment by bonomat** [comment]
> Alternatively, we can also use the testnet quotes consistently. e.g. the candlestick chart always shows mainnet prices. Also the testnet quotes do not change that often, thats why I sometime thought the maker was down.

If this bothers you, I'd rather go for showing a different candle chart.

**Review by bonomat — APPROVED** [review]
Too easy :)

**Pull request merged**
