### PR TITLE
Format sats in create invoice screen

### LINKED ISSUE #803: Add separators to min/max/recommended fund amount
Similar to how `AmountText` separates by `,`, we should separate these too, otherwise it is very difficult to see what these mean: 
image

### PR DESCRIPTION
**Pull request by Restioson**
Fixes #803.

### CODE REVIEW

**Comment by Restioson** [comment]
This is how it looks with the PR

image

**Review by holzeis — APPROVED** [review]
LGTM 👍

**Comment by Restioson** [comment]
I think my dart might be of a different version which is why this formatting is different to locally?

**Comment by Restioson** [comment]
I think the lnd-dlc-node-tests failure is irrelevant since I didn't change anything Rust-side here.

**Comment by holzeis** [comment]
> I think the lnd-dlc-node-tests failure is irrelevant since I didn't change anything Rust-side here.

Yes, we have unfortunately somewhat flaky tests at the moment. see also #774 and #775.

**Pull request merged**
