### PR TITLE
Add LN close buttons to app's settings page

### PR DESCRIPTION
**Pull request by luckysori**
Related to #410.

This is extremely dumb at the moment, but it worked nicely for testing as it allowed me to keep going without having to wipe any data.

### CODE REVIEW

**Review by klochowicz — APPROVED** [review]
I like it. Does the job 👍

**Comment by bonomat** [comment]
Let's put this on hold for now and force users to reach out to us if they get stuck. This way we have a chance to learn more then if they try to forc close and we don't hear anything from them.

**Comment by klochowicz** [comment]
as @luckysori pointed out in the PR, making testing easier is big plus. 

@bonomat @holzeis would you guys be ok if we only showed these buttons on regtest?

**Comment by bonomat** [comment]
> @bonomat @holzeis would you guys be ok if we only showed these buttons on regtest for now?

Yes, we could do that .

**Comment by klochowicz** [comment]
@bonomat @da-kami can I merge this? I added a flag that only shows it on regtests builds for now, and at least it will not need rebasing again...

**Comment by klochowicz** [comment]
going ahead, as it does not affect production in any way.

bors r+

**Pull request merged**
