### PR TITLE
fix: small layout bug

### PR DESCRIPTION
**Pull request by bonomat**
<table>
  <tr>
    <th>Before</th>
    <th>After</th>
  </tr>
  <tr>
    <td>
      image
    </td>
    <td>
      image
    </td>
  </tr>
</table>

### CODE REVIEW

**Comment by holzeis** [comment]
🤔 is this really a bug? Is the label now jumping with the amount? Or is it already doing that?

**Comment by bonomat** [comment]
Don't you see the big space between `Fee:` and `17,880`? Or are you saying this was by design, because I find it quite weird 😅

image

**Comment by holzeis** [comment]
> Don't you see the big space between `Fee:` and `17,880`? Or are you saying this was by design, because I find it quite weird 😅
> 
> 
> 
> image
> 
> 

I think it's by design so that the label is not jumping when the fee amount is changing.

**Comment by bonomat** [comment]
> I think it's by design so that the label is not jumping when the fee amount is changing.

Lol, and here I sit, thinking this is ugly as a hat full of bums.

**Pull request closed without merging**
