### PR TITLE
Roll back DB transaction if resize protocol start fails 

### PR DESCRIPTION
**Pull request by bonomat**
If we do this we are less likely to have inconsistent state between the DB and the subchannel data.

We should do this in more places.

### CODE REVIEW

**Review by luckysori — COMMENTED** [review]
This looks like a fix so that we don't run into https://github.com/get10101/meta/issues/262, nice!

If you don't mind, I'm going to refactor it slightly and also test that it works. An automatic test seems out of the question, but I think I can manually reproduce the original bug.

**Comment by holzeis** [comment]
I also propose that we get rid of the task that lead to that issue originally.

Let's set the position to closed when processing the `CloseFinalize` resp. `CloseRevoke` message. IMHO that's easier to understand and maintain.

**Comment by luckysori** [comment]
> I also propose that we get rid of the task that lead to that issue originally.
> 
> Let's set the position to closed when processing the `CloseFinalize` resp. `CloseRevoke` message. IMHO that's easier to understand and maintain.

100% agree.

I was actually unable to reproduce the bug, although maybe @holzeis had better luck. It's a bit frustrating, but at this stage I think the `closed_positions.rs` task is at fault and removing it would be for the better.

**Comment by bonomat** [comment]
> Let's set the position to closed when processing the `CloseFinalize` resp. `CloseRevoke` message. IMHO that's easier to understand and maintain.

Oh, I misunderstood this task. I thought it was for cleaning up old positions. Totally agree with you that we should just update the db when receiveing `CloseFinalize` .

**Comment by bonomat** [comment]
> > I also propose that we get rid of the task that lead to that issue originally.
> > Let's set the position to closed when processing the `CloseFinalize` resp. `CloseRevoke` message. IMHO that's easier to understand and maintain.
> 
> 100% agree.
> 
> I was actually unable to reproduce the bug, although maybe @bonomat had better luck. It's a bit frustrating, but at this stage I think the `closed_positions.rs` task is at fault and removing it would be for the better.

I was able to reproduce it here: https://github.com/get10101/10101/pull/1740

**Comment by bonomat** [comment]
@luckysori : did you say today you would like to see this change happening but refactor it a bit?

**Comment by luckysori** [comment]
> @luckysori : did you say today you would like to see this change happening but refactor it a bit?

Yep, I can push a couple changes to this PR later.

**Comment by luckysori** [comment]
I've refactored as discussed, @bonomat. You can't give approval to your own PR, but let me know if this is okay.

**Review by bonomat — COMMENTED** [review]
If this works, let's get it in. Thanks @luckysori

**Review by luckysori — APPROVED** [review]
Approved on behalf of @bonomat!

**Pull request merged**
