### PR TITLE
fix: improving wallet sync by 100x

### PR DESCRIPTION
**Pull request by bonomat**
Resolves [#710](https://github.com/get10101/10101/issues/710)

### CODE REVIEW

**Comment by holzeis** [comment]
@bonomat shouldn't we first wait if it is working with the coordinator?

**Comment by bonomat** [comment]
> @bonomat shouldn't we first wait if it is working with the coordinator?

Already done, works great on the coordinator :) 

Spot when we switched to our self-hosted node:

```
{"timestamp":"2023-09-05T09:32:52.146679125Z","level":"INFO","fields":{"message":"Finished on-chain sync","duration":"2177"},"target":"ln_dlc_node::ldk_node_wallet"}
{"timestamp":"2023-09-05T09:22:49.968838909Z","level":"INFO","fields":{"message":"Finished on-chain sync","duration":"4826"},"target":"ln_dlc_node::ldk_node_wallet"}
{"timestamp":"2023-09-05T09:19:12.783714036Z","level":"INFO","fields":{"message":"Finished on-chain sync","duration":"174384"},"target":"ln_dlc_node::ldk_node_wallet"}
{"timestamp":"2023-09-05T08:36:11.688759862Z","level":"INFO","fields":{"message":"Finished on-chain sync","duration":"151121"},"target":"ln_dlc_node::ldk_node_wallet"}

```

**Review by holzeis — APPROVED** [review]
🚀

**Comment by bonomat** [comment]
Rebasing...

**Pull request merged**
