### PR TITLE
chore: bump sdk

### PR DESCRIPTION
**Pull request by bonomat**
Locally I can only publish it if minSDK = 33. Let's see what CI says about the other "fix" before we merge this.

### CODE REVIEW

**Comment by holzeis** [comment]
Weird, locally it worked for me with minSDK = 31

**Comment by bonomat** [comment]
> Weird, locally it worked for me with minSDK = 31

Can you also publish it?

**Comment by holzeis** [comment]
> > Weird, locally it worked for me with minSDK = 31
> 
> Can you also publish it?

No because I was running into that error

```
Could not find fastlane-2.214.0, cocoapods-1.10.2, CFPropertyList-3.0.6, addressable-2.8.5, aws-sdk-s3-1.132.0, excon-0.100.0, faraday-1.10.3, fastimage-2.2.7, google-apis-androidpublisher_v3-0.47.0, google-apis-playcustomapp_v1-0.13.0, json-2.6.3, jwt-2.7.1, multipart-post-2.3.0, plist-3.7.0, simctl-1.6.10, cocoapods-core-1.10.2, cocoapods-deintegrate-1.0.5, cocoapods-downloader-1.6.3, cocoapods-plugins-1.0.0, cocoapods-search-1.0.1, cocoapods-trunk-1.6.0, cocoapods-try-1.2.0, escape-0.0.4, fourflusher-2.3.1, molinillo-0.6.6, nap-1.1.0, ruby-macho-1.4.0, rexml-3.2.6, public_suffix-5.0.3, aws-sdk-core-3.180.1, aws-sdk-kms-1.71.0, aws-sigv4-1.6.0, google-apis-core-0.11.1, digest-crc-0.6.5, google-apis-iamcredentials_v1-0.17.0, googleauth-1.7.0, activesupport-5.2.8.1, algoliasearch-1.27.5, concurrent-ruby-1.2.2, fuzzy_match-2.0.4, netrc-0.11.0, typhoeus-1.4.0, aws-partitions-1.798.0, webrick-1.8.1, google-cloud-errors-1.3.1, i18n-1.14.1, minitest-5.19.0, tzinfo-1.2.11, ethon-0.16.0, thread_safe-0.3.6, ffi-1.15.5 in locally installed gems
Run `bundle install` to install missing gems.
```

**Comment by bonomat** [comment]
> > > Weird, locally it worked for me with minSDK = 31
> > 
> > 
> > Can you also publish it?
> 
> No because I was running into that error
> 
> ```
> Could not find fastlane-2.214.0, cocoapods-1.10.2, CFPropertyList-3.0.6, addressable-2.8.5, aws-sdk-s3-1.132.0, excon-0.100.0, faraday-1.10.3, fastimage-2.2.7, google-apis-androidpublisher_v3-0.47.0, google-apis-playcustomapp_v1-0.13.0, json-2.6.3, jwt-2.7.1, multipart-post-2.3.0, plist-3.7.0, simctl-1.6.10, cocoapods-core-1.10.2, cocoapods-deintegrate-1.0.5, cocoapods-downloader-1.6.3, cocoapods-plugins-1.0.0, cocoapods-search-1.0.1, cocoapods-trunk-1.6.0, cocoapods-try-1.2.0, escape-0.0.4, fourflusher-2.3.1, molinillo-0.6.6, nap-1.1.0, ruby-macho-1.4.0, rexml-3.2.6, public_suffix-5.0.3, aws-sdk-core-3.180.1, aws-sdk-kms-1.71.0, aws-sigv4-1.6.0, google-apis-core-0.11.1, digest-crc-0.6.5, google-apis-iamcredentials_v1-0.17.0, googleauth-1.7.0, activesupport-5.2.8.1, algoliasearch-1.27.5, concurrent-ruby-1.2.2, fuzzy_match-2.0.4, netrc-0.11.0, typhoeus-1.4.0, aws-partitions-1.798.0, webrick-1.8.1, google-cloud-errors-1.3.1, i18n-1.14.1, minitest-5.19.0, tzinfo-1.2.11, ethon-0.16.0, thread_safe-0.3.6, ffi-1.15.5 in locally installed gems
> Run `bundle install` to install missing gems.
> ```

Try follow the recommended ways in [here](https://docs.fastlane.tools/getting-started/ios/setup/) using the bundle installer

**Comment by bonomat** [comment]
Interestingly, CI seems to be fine and the build works on my Android 13 phone.

**Pull request closed without merging**
