### PR TITLE
Fund maker and open channel

### PR DESCRIPTION
**Pull request by bonomat**
This comes handy if LND doesn't work as expected.

You can then use `curl -X POST http://localhost:18000/api/pay-invoice/putinvoicehere` to pay any invoices and fund the app. 

Or you can use the new `fund with maker button` :) 

image

### CODE REVIEW

**Review by holzeis — APPROVED** [review]
Makes sense, I am not happy to see that lnd just doesn't want to work reliably on regtest, but I guess that's the way to go to unblock us in many situations.

**Comment by luckysori** [comment]
Might be nice to add another button on regtest builds. And maybe to fund the maker with `just fund` too.

**Comment by holzeis** [comment]
> This comes handy if LND doesn't work as expected.
> 
> 
> 
> You can then use `curl -X POST http://localhost:18000/api/pay-invoice/putinvoicehere` to pay any invoices and fund the app. 

As far as I can tell the maker is funded, otherwise it couldn't open a channel to the coordinator.

I agree on the button although what do we keep lnd then around for? 🙈

**Comment by bonomat** [comment]
> I agree on the button although what do we keep lnd then around for? 🙈

I opted for keeping it around ;)

**Pull request merged**
